### PR TITLE
Show incoming call activity over the lock screen

### PR DESCRIPTION
**Pull request by juanitobananas**
I think this would be pretty cool and would make it more similar to how other telephony apps work.

Cheers,
Juanito

### CODE REVIEW

**Comment by juanitobananas** [comment]
Of course, this could lead to picking calls without actually wanting too. A swipe thingie to pick up would be nice together with this.

**Comment by ylecollen** [comment]
This update must be set by a global settings. I don't want that someone complains that the call has be accepted whereas his phone was in his pocket.

Which android version did you test ?

**Comment by juanitobananas** [comment]
> This update must be set by a global settings. I don't want that someone complains that the call has be accepted whereas his phone was in his pocket.

Of course, that shouldn't be a big deal.

> Which android version did you test ?

I tested it with CM13 (roughly similar to Android 6.0.1).

**Comment by juanitobananas** [comment]
I just tested it with an Android 5 and it doesn't seem to be working so I'll take a look at it and open a new PR if I find a solution to this.

**Pull request closed without merging**
