### PR TITLE
Refactor push system

### PR DESCRIPTION
**Pull request by krombel**
The GcmRegistrationManager did much more than just handling the GCM registration.
Here the general part of push management gets split out of it to make it easier
to implement another approach of a push notification system.

Signed-Off-by: Matthias Kesler <krombel@krombel.de>

### CODE REVIEW

**Comment by bmarty** [comment]
Hi @krombel ,

Thanks for this PR. I thinks its a good idea.

Unfortunatly, there is a lot of conflicting files, due to the delay to answer to your PR (sorry about that).

Please fix the conflicts by rebasing your code and I'll check again this PR

Benoît

**Comment by krombel** [comment]
@bmarty I have updated and now tested the implementation for FCM.
Feel free to review now

**Comment by bmarty** [comment]
This PR is mainly obsolete now (see #2706).
There is still some interesting things about generic Push manager we can get later.

**Comment by krombel** [comment]
This looks like a step in the right direction.
I will close this for now.

**Pull request closed without merging**
