### PR TITLE
Bug Fix Privacy: Riot should never pass events content to GCM

### PR DESCRIPTION
**Pull request by giomfo**
Add another setting when background sync is disabled: "Keep full detailed notifications" with a subtitle "This requires to send non encrypted message content through Google services servers".

#2051

### CODE REVIEW

**Comment by giomfo** [comment]
@manuroe what do you think to move this new setting in the `Notifications` section?
(It would be hidden if background sync is enabled)

**Comment by giomfo** [comment]
Updated settings display:
screen shot 2018-03-09 at 10 40 35

**Comment by Tyuoli** [comment]
It may be necessary to inform the user of the interest of activating or not the option of background sync. 
For example, we could specify the interest of not depending on Google for notifications and / or the interest of saving the battery.

**Comment by manuroe** [comment]
The notification is really poor. But I can understand that the android code is not ready to provide the display name of the room without loading everything from the store.

**Comment by giomfo** [comment]
@manuroe @Tyuoli : please review my last commit in this PR. The aim is to improve the notifications when the background sync is disabled.
The room name is now displayed:
screen shot 2018-03-10 at 01 37 31

**Comment by hrj** [comment]
@giomfo @manuroe Thanks for seeing this through :heart:

**Pull request merged**
