### PR TITLE
Start on boot if background sync is allowed and GCM is not supported

### LINKED ISSUE #319: Listen for events on boot
Firstly, thanks for your work.

Please, could you add an option to start to listen events on boot?

Thank you.

### PR DESCRIPTION
**Pull request by Unrud**
Basically the same as #838 but only for the FDroid flavor and with some additional checks. (Fixes #319)

### CODE REVIEW

**Comment by ylecollen** [comment]
It might work only for the Fdroid clients.
Your implementation does not check if the installed app is the Google play or the Fdroid one.

**Comment by Unrud** [comment]
> Your implementation does not check if the installed app is the Google play or the Fdroid one.

All changes are in the folder *vector/src/**appfdroid**/*.

**Comment by ylecollen** [comment]
Sorry, i did not notice it.
But, i think it should be optional : we need to have a settings entry to let the user to decide.

**Comment by Unrud** [comment]
I moved the code from **appfroid** to **main** and instead added a check for GCM support.

> But, i think it should be optional : we need to have a settings entry to let the user to decide.

Done. (Although I think the option is superfluous, you can already disable background sync.)

**Comment by ylecollen** [comment]
It does not work on a nexus 5X (android 7.1)

**Comment by ylecollen** [comment]
i rewrote a part of your code because the develop branch has been updated a lot since this PR.
https://github.com/vector-im/riot-android/commit/2ea7205195de12899572766d5d401294e0598fc1

**Pull request closed without merging**
