### PR TITLE
Do not ring if "Do Not Disturb" is active

### PR DESCRIPTION
**Pull request by juanitobananas**
Signed-off-by: Juan García Basilio <juanitobananas@gmail.com>

EDIT: add sign-off

### CODE REVIEW

**Comment by BloodyIron** [comment]
Anyone looking at this? D:

**Comment by bmarty** [comment]
Hi @juanitobananas , thanks for this PR
Could you please sign-off it as per https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.rst#sign-off
Benoît

**Comment by bmarty** [comment]
Hi @juanitobananas ,

It's a shame to close this PR, it was a good idea. I can handle the merge issue, and you can just sign-off by adding a comment in this pull request as follow:

`Signed-off-by: Your Name <your@email.example.org>`

Thanks
Benoît

**Comment by juanitobananas** [comment]
Hey Benoît!

> It's a shame to close this PR, it was a good idea.

I am glad you like it. I thought so too :smile:

>I can handle the merge issue, and you can just sign-off by adding a comment in this pull request

That should be no problem at all. I'll gladly sign it off. You really don't need to worry to add it to the commit. Just copy as much as you can: I am sure the patch will actually more yours than mine :wink:

Cheers,
Juanito

**Comment by bmarty** [comment]
Related to #1072

**Comment by bmarty** [comment]
Closed and replaced by #2368

**Pull request closed without merging**
