### PR TITLE
Fix typo in catalan translation

### PR DESCRIPTION
**Pull request by tsdgeos**

### CODE REVIEW

**Comment by tsdgeos** [comment]
@jmallach is this going to work or do i have to use that weird webapp for translating?

**Comment by jmallach** [comment]
I have no idea, may be safest to do it in weblate. I can do it if you like.

**Comment by tsdgeos** [comment]
@jmallach If you think that's best, lets go for it

**Comment by tsdgeos** [comment]
@jmallach if you haven't fixed it yet, found another typo

 <string name="directory_search_results_title">Navega pel directpri</string>

directpri → directori

**Comment by bmarty** [comment]
Hi @tsdgeos ,
Thanks for the fix. I can accept PR to fix small typos in translation, but the normal way is to use Weblate. I assume it will trigger notification to other translators about the modification they can then check.
You can commit again to fix @tsdgeos suggestions if you think i's ok.
I'll then merge this PR
Thanks
Benoit

**Comment by tsdgeos** [comment]
@bmarty not really interested in having yet another login in yet another system and learning to use yet another tool when i could just fix it in the source code.

If that's not valid, as i said i'll be really happy if @jmallach does the fix via weblate.

**Comment by jmallach** [comment]
I have corrected these two typos in weblate. Many thanks, @tsdgeos!

**Comment by bmarty** [comment]
Fix will come with next Weblate merge

**Pull request closed without merging**
