### PR TITLE
Enable building with Jack

### PR DESCRIPTION
**Pull request by spacekitteh**
jackInProcess is set to false, as I'm pretty sure this allows it to attach to an existing Jack server.

### CODE REVIEW

**Comment by ylecollen** [comment]
http://tools.android.com/tech-docs/jackandjill 
Jack build chain is still experimental so i'm not sure that it is safe to use it.

Did you already use it in other projects ?

**Comment by spacekitteh** [comment]
Yes, it is the default build chain for AOSP 7.0 and up. :)

**Comment by ylecollen** [comment]
our target SDK is still 23 so i prefer to keep the default build chain until we support the target API becomes 24/

**Comment by jcgruenhage** [comment]
Actually, JACK has been deprecated, in case you didn't notice, so switching to JACK now wouldn't do any good.

**Comment by bmarty** [comment]
Jack is deprecated, I close this PR

**Pull request closed without merging**
