### PR TITLE
add portuguese language

### PR DESCRIPTION
**Pull request by dtygel**
Created infrastructure to allow translations to portuguese.

### CODE REVIEW

**Comment by ara4n** [comment]
@ylecollen please let's merge it, and see how well the community translations end up being maintained by the community.

**Comment by dtygel** [comment]
If you want, I can try to achieve at least 80% of the translation, and the merge would be more meaningful.

**Comment by ylecollen** [comment]
dtygel : i merged your translations on the develop branch.

**Comment by ylecollen** [comment]
@dtygel : could you translate the remaining sentences ?

thank you

**Comment by dtygel** [comment]
Yes. I'll do it ASAP.

**Comment by dtygel** [comment]
@ylecollen : done. https://github.com/vector-im/riot-android/pull/1101

Thanks!

**Pull request closed without merging**
