### PR TITLE
Complete Italian translation with newer strings about stickers

### PR DESCRIPTION
**Pull request by Silvan87**
I took the strings.xml file in English and translated all the new strings, I also converted the four spaces with a single tab.

### CODE REVIEW

**Comment by Silvan87** [comment]
Is there any problem? It's just an updated file of strings...

**Comment by bmarty** [comment]
Hi @Silvan87,

Thanks for the PR.

You can view why CI failed by clicking on the link [Details](https://travis-ci.org/vector-im/riot-android/builds/384168096?utm_source=github_status&utm_medium=notification).

You'll see the error in the logs:

```
  The first 3 errors (out of 5) were:
  /home/travis/build/vector-im/riot-android/vector/src/main/res/values-it/strings.xml:395: Error: Apostrophe not preceded by \ [StringEscaping]
   <string name="room_participants_ban_prompt_msg">Sei sicuro di voler proibire l'accesso alla chat a questo utente?</string>

...
```

The **'** char is not escaped.

Nevertheless I cannot merge your PR cause the string translations are managed with a external tool call [weblate](https://translate.riot.im/projects/riot-android/riot-android/). Maybe this information was not clear enough, I'll see how to improve this.

Benoît

**Comment by Silvan87** [comment]
Thanks for the explanation.
I can register there and add my local translation.

**Comment by bmarty** [comment]
Thanks @Silvan87 :)

**Pull request closed without merging**
