### PR TITLE
Tidy codebase

### PR DESCRIPTION
**Pull request by kaiyou**
While working on the application UI, I basically read through large sections of the codebase and try and improve the cosmetics from time to time, especially when I have to use some class that I do not understand at first sight because of its structure.

This pull request will contain all my cosmetic and structural changes to the codebase that do not actually change anything to the functionality of the application.

Signed-off-by: Pierre Jaury <pierre@jaury.eu>

### CODE REVIEW

**Comment by giomfo** [comment]
@kaiyou: thank for your contribution. Could you please sign off your PR (see https://github.com/vector-im/riot-android/blob/master/CONTRIBUTING.rst#sign-off)?

If you agree, all that's needed is to include the line in your commit or pull request comment:
Signed-off-by: Your Name your@email.example.org

**Comment by kaiyou** [comment]
Yes of course. Does this still merge without conflict though?

**Comment by giomfo** [comment]
There is no conflict for the moment ;)

**Comment by kaiyou** [comment]
Just added the sign-off to the PR, thanks for reviewing this.

**Pull request merged**
