### PR TITLE
Start riot automatically on boot

### PR DESCRIPTION
**Pull request by juanitobananas**
If not, you can't receive any messages until you open the app manually.

Unfortunately, you need a new permission for this.

Cheers,
Juanito

### CODE REVIEW

**Comment by ylecollen** [comment]
we need to add a settings to enable it at launch and it is only for the fdroid version.

**Comment by juanitobananas** [comment]
> we need to add a settings to enable it at launch

No problem, should I do it?

> it is only for the fdroid version

Oh, okay! I thought it was a general problem as I tested it with the Google Play version but there might've just been a GCM glitch due to uninstalling/reinstalling.

I am not sure how to do F-Droid-specific settings but I guess I'll be able to (I'll just take a look at the sync settings that are F-Droid-specific).

How can I build the F-Droid version to test it (I am currently using Android Studio)?

**Comment by Susurrus** [comment]
Can this be closed since 2ea7205195de12899572766d5d401294e0598fc1 was merged?

**Comment by juanitobananas** [comment]
> Can this be closed since 2ea7205 was merged?

Definitely! :smile:

**Pull request closed without merging**
