### PR TITLE
Piwik opt-out needs a restart

### PR DESCRIPTION
**Pull request by licaon-kter**
fix https://github.com/vector-im/riot-android/issues/2172

### CODE REVIEW

**Comment by bmarty** [comment]
Thanks for the PR. I'm not sure it will be merged for two reasons:
- String has to be edited with the Weblate tool
- The real fix should be to disable piwik without the necessity to restart application

**Comment by licaon-kter** [comment]
Workflow is usually github-weblate-translations to other that english, it is not like that here?

I agree, but in the meantime...

**Comment by bmarty** [comment]
I think piwik opt-out does not need a restart anymore. I'll check soon to safely close this PR

**Comment by bmarty** [comment]
Analytics has been improved, no restart is needed anymore

**Pull request closed without merging**
